---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-ipfs-0
  namespace: ipfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      app: ipfs
      petindex: "0"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-ipfs-1
  namespace: ipfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      app: ipfs
      petindex: "1"
