apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ipfs
  namespace: ipfs
spec:
  serviceName: ipfs
  replicas: 2
  template:
    metadata:
      labels:
        app: ipfs
    spec:
      containers:
      - name: ipfs
        image: ipfs/go-ipfs:v0.4.11@sha256:e977e1560b960933061efc694c937d711ce1a51aa4a5239acfdff01504b11054
        env:
        - name: IPFS_LOGGING
          value: debug
        #bootstrap#args:
        #bootstrap#- --offline
        #command:
        #- ipfs bootstrap rm --all
        ports:
        - containerPort: 4001
          name: swarm
        - containerPort: 5001
          name: api
        - containerPort: 8080
          name: readonly
        volumeMounts:
        - name: data
          mountPath: /data/ipfs
  volumeClaimTemplates:
  - metadata:
      name: data
      namespace: ipfs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi
