apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: ipfs
  namespace: ipfs
spec:
  serviceName: ipfs
  replicas: 2
  template:
    metadata:
      labels:
        app: ipfs
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
        pod.alpha.kubernetes.io/init-containers: '[
        ]'
    spec:
      containers:
      - name: ipfs
        image: ipfs/go-ipfs:v0.4.3-rc3
        env:
        - name: IPFS_LOGGING
          value: debug
        #bootstrap#args:
        #bootstrap#- --offline
        #command:
        #- ipfs bootstrap rm --all
        ports:
        - containerPort: 4001
          name: swarm
        - containerPort: 5001
          name: api
        - containerPort: 8080
          name: readonly
        volumeMounts:
        - name: datadir
          mountPath: /data/ipfs
  volumeClaimTemplates:
  - metadata:
      name: datadir
      namespace: ipfs
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi
